name: Symfony

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Prepare .env.test.local
        run: |
          if [ ! -f .env ]; then cp .env.test .env; fi
          if [ ! -f .env.test.local ]; then cp .env.test .env.test.local; fi

      - name: Prepare SQLite database
        run: |
          mkdir -p data
          touch data/database.sqlite

      - name: Run tests
        env:
          DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite
        run: vendor/bin/phpunit

      - name: Show Symfony logs on failure
        if: failure()
        run: cat var/log/test.log || echo "Log file not found"
